TBA command fixed + RegEx added for chants
IronRiders/discordbot pull request #7
Opened 2023-04-15 07:00 UTC by SBsteveyHops

Also, restarting might fix the commands not appearing.

2023-04-15 20:01 UTC, SBsteveyHops commented
this lib is needed https://github.com/RaiderRobotix/blue-alliance-api-java-library/releases/tag/v2.1

2023-04-19 03:41 UTC, johnluetke approved these changes

2023-04-19 04:03 UTC, johnluetke requested changes
Build failed, will be making necessary changes to this pull request

2023-09-06 03:29 UTC, ampersanded-dev commented
oops, wrong branch

2023-09-06 03:29 UTC, merged